djangoShopping/accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', LogoutView.as_view(),name= 'logout'),
    path('signup/', views.ESSignUp.as_view(), name='signup'),
    path('<int:pk>/', views.ESDetail.as_view(),name='userdetails'),
    path('edit/<int:pk>/', views.ESUpdateView.as_view(), name='useredit'),
    path('delete/<int:pk>/', views.ESDeleteView.as_view(), name='userdelete'),

]

djangoShopping/djangoShopping/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('loggedout/', views.AfterLogoutView.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('shoppinglists/', include('shoppingList.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoShopping/shoppingList/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views


app_name = 'shoplists'

urlpatterns = [

    path('new/', views.ShoppingListCreateView.as_view(), name='createlist'),
    path('by/<str:username>/', views.UserShoppingLists.as_view(), name='listsbyuser'),
    path('by/<str:username>/<int:pk>/', views.ShoppingListDetailView.as_view(), name='details'),
    # path('<int:pk>/', views.ESDetail.as_view(),name='userdetails'),
    path('edit/<int:pk>/', views.ShoppingListUpdateView.as_view(), name='listedit'),
    path('delete/<int:pk>/', views.ShoppingListDeleteView.as_view(), name='listdelete'),

]

djangoShopping/shoppingList/models.py
from django.db import models
from django.contrib import auth
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase
from django.utils.timezone import now

User = get_user_model()
# Create your models here.


class TaggedShoppingList(TaggedItemBase):
    content_object = models.ForeignKey('ShoppingList', on_delete=models.CASCADE)
    checked = models.BooleanField(default=False)


class ShoppingList(models.Model):

    author = models.ForeignKey(User, related_name='shoplists', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=False)
    # products = TaggableManager(help_text="Type your comma-separated list of products", verbose_name="Products")
    products = TaggableManager(through=TaggedShoppingList, help_text="Type your comma-separated list of products", verbose_name="Products")
    created_date = models.DateTimeField(default=now, editable=False)
    edit_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('shoplists:listsbyuser', kwargs={'username': self.author.username})

    def products_as_list(self):
        listobject = []
        for item in self.products.all():
            listobject.append(item.name)

        return listobject

djangoShopping/shoppingList/views.py
import datetime

from . import models
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.http import Http404
from django.urls import reverse_lazy, reverse

User = get_user_model()

# Create your views here.
class ShoppingListCreateView(CreateView,LoginRequiredMixin, SelectRelatedMixin):
    # ten widok powstał z pominięciem tworzenia formularza

    model = models.ShoppingList
    fields = ('title', 'products')
    template_name = 'shoppingList/create.html'

    labels = {
        'products': 'Please type comma-separated list of products'
    }

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class UserShoppingLists(ListView):
    model = models.ShoppingList
    template_name = 'shoppingList/lists_by_user.html'
    ordering = ['+created_date']

    def get_queryset(self):
        try:
            self.list_user = User.objects.prefetch_related('shoplists').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.list_user.shoplists.all().order_by('-created_date')

    # nadpisanie tej metody pozwala dodać ekstra informacje do widoku listy
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_user'] = self.list_user
        return context


class ShoppingListDetailView(SelectRelatedMixin, DetailView):
    model = models.ShoppingList
    template_name = 'shoppingList/list_detail.html'
    select_related = ('author',)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author__username__iexact=self.kwargs.get("username"))


class ShoppingListUpdateView(UpdateView,SelectRelatedMixin):
    model = models.ShoppingList

    fields = ('title', 'products')
    template_name = 'shoppingList/edit_list.html'
    redirect_field_name = 'shoppingList/list_detail.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.edit_date = datetime.datetime.now()
        self.object.save()
        return super().form_valid(form)


class ShoppingListDeleteView(DeleteView, SelectRelatedMixin):
    model = models.ShoppingList
    template_name = 'shoppingList/list_confirm_delete.html'
    # success_url = reverse_lazy('shoplists:listsbyuser', kwargs={'username': User.username})
    select_related = ('author',)

    def delete(self, request, *args, **kwargs):
        # the Post object
        self.object = self.get_object()
        if self.object.User == request.user:
            success_url = self.get_success_url()
            self.object.delete()
        #     return http.HttpResponseRedirect(success_url)
        # else:
        #     return http.HttpResponseForbidden("Cannot delete other's posts")

    def get_success_url(self):
        return reverse('shoplists:listsbyuser', kwargs={'username': self.object.author.username})

djangoShopping/shoppingList/templates/shoppingList/create.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}

{% block content %}
<div class="container">
   <h1>Create new shopping list</h1>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-lg"><i class="fa-solid fa-save fa-1.5"></i> Save</button>
    </form>
</div>

{%  endblock %}

djangoShopping/shoppingList/templates/shoppingList/edit_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}

{% block content %}
<div class="container">
   <h1>Create new shopping list</h1>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-lg"><i class="fa-solid fa-save fa-1.5"></i> Save</button>
    </form>
</div>

{%  endblock %}

djangoShopping/shoppingList/templates/shoppingList/list_confirm_delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}

{% block content %}
<div class="container">
   <h1>Confirm shopping list removal</h1>
<div class="row" style="height:200px">
        <div class="col-md-8 userinfocol">
            <div id="userinfo">
                    <h5>Are you sure you want to delete <span class="username">{{ shoppinglist.title }}</span>?</h5>
                <hr style="border-top: 1px solid white;">
                <form method="POST">
                    {%  csrf_token %}
                <div class="stackedbutton"><button onclick="window.location='{% url 'shoplists:listsbyuser' username=user.username %}'" type="button" class="btn btn-primary"><i class="fa-solid fa-times fa-1.5"></i> Cancel</button> </div>
                <br>
                <div class="stackedbutton"><button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash fa-1.5"></i> Delete</button> </div>
                </form>
            </div>


        </div>
        <div class="col-md-4 userinfocol" id="userphoto">

        </div>

    </div>
</div>

{%  endblock %}

djangoShopping/shoppingList/templates/shoppingList/list_detail.html
{% extends 'base.html' %}

{%  load bootstrap5 %}
{% load static %}
{% load tz %}


{% block content %}
    {%  debug %}
    <h1 id="test">Shopping list details</h1>
    <div class="row">
        <div class="col-md-4 userinfocol">
            <div id="userinfo">
                    <h4><span class="username">{{ shoppinglist.title }}</span></h4>
                <hr style="border-top: 1px solid white;">
                    <p id="line"><strong>Author: </strong> {{ shoppinglist.author }}</p>
                    <p><strong>Created: </strong> {{ shoppinglist.created_date|timezone:"Europe/Paris"|date:'H:i d.m.y' }}</p>
                    {% if shoppinglist.edit_date is not null %}
                    <p><strong>Edited: </strong> {{ shoppinglist.edit_date|timezone:"Europe/Paris"|date:'H:i d.m.y' }}</p>
                    {%  endif %}
            </div>

            <div id="userbuttons">
                <h4 style="text-align:center">Shopping list operations</h4>
                <hr style="border-top: 1px solid white;">
                <a href="{%  url 'shoplists:listedit' pk=shoppinglist.pk %}">
                <div class="stackedbutton"><button class="btn btn-danger" style="background-color: #f39c12"><i class="fa-solid fa-edit fa-1.5"></i> Edit list</button> </div> </a>
                <br>
                <a href="{%  url 'accounts:userdelete' pk=object.pk %}">
               <div class="stackedbutton"><button type="button" class="btn btn-danger"><i class="fa-solid fa-trash fa-1.5"></i> Delete list</button> </div>
                </a>
            </div>
        </div>
        <div class="col-md-6 userinfocol productsinfo" >
            <ul class="list-group">
            {%  for product in shoppinglist.products_as_list %}
                <li class="list-group-item singleproduct" ><input class="form-check-input me-1 productcheckbox" type="checkbox"> {{ product }}</li>


            {% endfor %}
            </ul>
        </div>



    </div>


{%  endblock %}

djangoShopping/shoppingList/templates/shoppingList/lists_by_user.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}
{% load tz %}

{% block content %}
<div class="container">
{#    {% debug %}#}
    {% if shoppinglist_list.count  == 0 %}
   <h1><span class="username">{{user.username}}</span>, it seems you haven't created any list so far...</h1>
        <h2>Make shopping easy by creating one!</h2>

    {% else %}
   <h1><span class="username">{{user.username}}</span>, you have created <span class="badge postcountbadge" >{{ shoppinglist_list.count }}</span> list{{ shoppinglist_list.count|pluralize }}:</h1>


    <div class="row">
        {% for item in shoppinglist_list %}
        <div class="col-auto mb-3">
            <div class="card" style="width: 21rem; height: 15rem;">
                <div class="card-body" style="position:relative;">
                    <h5 class="card-title">{{item.title|truncatechars:25}}</h5>
                    <hr style="border-top: 1px solid white;">
                    <h6 class="card-subtitle mb-2 text-muted" style="text-align: right">{{ item.created_date|timezone:"Europe/Paris"|date:'H:i d.m.y' }}</h6>
                    <p class="card-text">{{ item.products.all|join:", "|truncatechars:90}}</p>

                    <div class="buttons-flex" >
                        <a href="{% url 'shoplists:details' username=item.author.username pk=item.pk %}">
                        <div class="listbutton"><button class="btn btn-primary"><i class="fa-solid fa-eye fa-1.5"></i> View </button> </div> </a>

                        <a href="{%  url 'shoplists:listedit' pk=item.pk %}">
                        <div class="listbutton"><button class="btn btn-danger" style="background-color: #f39c12"><i class="fa-solid fa-edit fa-1.5"></i> Edit </button> </div> </a>

                        <a href="{%  url 'shoplists:listdelete' pk=item.pk %}">
                       <div class="listbutton"><button type="button" class="btn btn-danger"><i class="fa-solid fa-trash fa-1.5"></i> Delete </button> </div>
                    </a>
                        </div>
                </div>
            </div>
        </div>
        {%  endfor %}
    </div>


    {%  endif %}
</div>

{%  endblock %}

djangoShopping/shoppingList/templates/shoppingList/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>