djangoShopping/accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', LogoutView.as_view(),name= 'logout'),
    path('signup/', views.ESSignUp.as_view(), name='signup'),
    path('<int:pk>/', views.ESDetail.as_view(),name='userdetails'),
    path('edit/<int:pk>/', views.ESUpdateView.as_view(), name='useredit'),
    path('delete/<int:pk>/', views.ESDeleteView.as_view(), name='userdelete'),

]

djangoShopping/djangoShopping/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('loggedout/', views.AfterLogoutView.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('shoppinglists/', include('shoppingList.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoShopping/shoppingList/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views


app_name = 'shoplists'

urlpatterns = [

    path('new/', views.ShoppingListCreateView.as_view(), name='createlist'),
    path('by/<str:username>/', views.UserShoppingLists.as_view(), name='listsbyuser'),
    path('by/<str:username>/<int:pk>/', views.ShoppingListDetailView.as_view(), name='details'),
    # path('<int:pk>/', views.ESDetail.as_view(),name='userdetails'),
    path('edit/<int:pk>/', views.ShoppingListUpdateView.as_view(), name='listedit'),
    path('delete/<int:pk>/', views.ShoppingListDeleteView.as_view(), name='listdelete'),

]

djangoShopping/templates/base.html
<!DOCTYPE html>
{%  load static %}
{%  load bootstrap5 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Easy Shopper</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/f25ade78d7.js" crossorigin="anonymous"></script>
  {% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/css/master.css' %}">
    <script src="{% static '/js/master.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static '/accounts/css/accounts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/shoppingList/css/shoppinglists.css' %}">
</head>
<body>


	<nav class="navbar navbar-expand-sm navbar-dark bg- navbar-custom">
	  <div class="container-fluid ">
		<a class="navbar-brand " href="{%  url 'home' %}" style="color:#fca311"><i class="fa-solid fa-cart-shopping fa-1.5x" style="color:#fca311"></i>  Easy Shopper</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>

          <ul class="navbar-nav ml-auto">
              {%  if user.is_authenticated %}
              <li class="nav-item">
			  <a class="nav-link" href="{% url 'shoplists:listsbyuser' username=user.username %}"><i class="fa-solid fa-rectangle-list fa-1.5"></i> Your lists</a>
			</li>
              <li class="nav-item">
			  <a class="nav-link" href="{% url 'shoplists:createlist' %}"><i class="fa-solid fa-square-plus fa-1.5"></i>  New list</a>
			</li>
                  <li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:userdetails' pk=user.pk%}"><i class="fa-solid fa-user fa-1.5"></i> Your account</a>
			</li>
              {% endif %}
          </ul>

		<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            {%  if user.is_authenticated %}
              <ul class="navbar-nav ">
                  <span style="color:#fca311" class="navbar-text">Welcome {{ user.username }}!</span>
              <li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="fa-solid fa-right-from-bracket fa-1.5"></i>  Log out</a>
			</li>
              {% else %}

		  <ul class="navbar-nav ">
            <li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:signup' %}"><i class="fa-solid fa-user-plus fa-1.5"></i>  Sign up</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:login' %}"><i class="fa-solid fa-right-to-bracket fa-1.5"></i>  Log in</a>
			</li>
          </ul>
                  {% endif %}


		  </ul>
		</div>
	  </div>
	</nav>
</body>
</html>



<div class="container" style="margin-top:30px">
{% block content %}

{% endblock %}

</div>

<footer class=" text-white fixed-bottom" style="background-color: #14213d; text-align:center">

  <!-- Grid container -->
{#  <div class="container p-1"></div>#}
  <!-- Grid container -->

    <div class="row">
        <div class="col-md-11">     © 2022 Copyright:
    <a class="text-white" href={% url 'home' %}>Easy Shopper</a></div>
        <div class="col-md-1"> <a href={% url 'admin:index' %} style="text-align:right;"><i class="fa-solid fa-lock fa-1.5" style="color:#fca311"></i></a></div>
    </div>


  <!-- Copyright -->
</footer>

</body>
</html>

djangoShopping/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Shopping lists. <strong>Made easy. </strong> </h1>



    <div class="row"  style="margin-top:2em">
    <div class="col-md-3">
        <div class="counter-card" style="margin-top:0; width:auto; height: 46%;">
                <div class="card-body" >
                    <div class="counter">
                      <i class="fa fa-people-group fa-3x"></i>
                      <h2 class="timer count-title count-number" data-to={{ user_count }} data-speed="1500"></h2>
                       <p class="count-text ">Registered Members</p>
                    </div>



                </div>
            </div>

        <div class="counter-card" style=" width:auto; height: 46%;">
                <div class="card-body" >
                    <div class="counter">
                      <i class="fa fa-list-check fa-3x"></i>
                      <h2 class="timer count-title count-number" data-to={{ lists_count }} data-speed="1500"></h2>
                       <p class="count-text ">Shopping lists created</p>
                    </div>



                </div>
            </div>
    </div>

    <div class="col-md-8" >
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="6000" >
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" style="border-radius: 10px;">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'images/1.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/2.jpg' %}"  alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/3.jpg' %}"  alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

    </div>
    </div>
    </div>

{% endblock %}

djangoShopping/templates/thanks.html
<!DOCTYPE html>
{%  extends 'base.html' %}
{% block content %}
<div class="container">
   <h1>Thanks for visiting.</h1>
    <h2>See you soon!</h2>
</div>

{%  endblock %}