djangoShopping/accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', LogoutView.as_view(),name= 'logout'),
    path('signup/', views.ESSignUp.as_view(), name='signup'),
    path('<int:pk>/', views.ESDetail.as_view(),name='userdetails'),
    path('edit/<int:pk>/', views.ESUpdateView.as_view(), name='useredit'),
    path('delete/<int:pk>/', views.ESDeleteView.as_view(), name='userdelete'),

]

djangoShopping/djangoShopping/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('loggedout/', views.AfterLogoutView.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('shoppinglists/', include('shoppingList.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoShopping/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.
from django.urls import reverse_lazy, reverse


class ESUser(auth.models.User, auth.models.PermissionsMixin):

    SEXES = [('M','male'),('F','female'),('O','other')]

    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
        return 'profiles/user_{0}/{1}'.format(instance.pk,filename)

    origin = models.CharField(max_length=50, blank=False, null=False)
    sex = models.CharField(choices=SEXES, max_length=1)

    # profile_pic = models.ImageField(upload_to=user_directory_path, default='profiles/default_pic.png',blank=True)
    profile_pic = models.ImageField(upload_to=user_directory_path, blank=False)

    def __str__(self):
        return "@{}".format(self.username)

    def get_absolute_url(self):
        return reverse('accounts:userdetails', kwargs={'pk': self.pk})

djangoShopping/accounts/forms.py
from django.contrib.auth import get_user_model
from . models import ESUser
from django.contrib.auth.forms import UserCreationForm
from django import forms


class ESUserCreationForm(UserCreationForm):

    # dodanie ekstra pól do modelu uzytkownika
    class Meta:
        model = ESUser
        # fields = UserCreationForm.fields + ('origin', 'sex')
        fields = ['username',  'sex', 'password1', 'password2', 'email', 'origin', 'profile_pic']

        widgets = {
            'sex': forms.Select(attrs={'class': 'bootstrap-select'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__( *args, **kwargs)
        self.fields['username'].label = 'Enter your name'
        self.fields['email'].label = 'Enter your email address'
        self.fields['origin'].label = 'Input your country of origin'

djangoShopping/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from . import models
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
# Create your views here.


class ESSignUp(CreateView):
    form_class = forms.ESUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:login')


class ESDetail(LoginRequiredMixin, DetailView):
    model = models.ESUser
    template_name = 'accounts/user_detail.html'


class ESUpdateView(LoginRequiredMixin, UpdateView):
    model = models.ESUser
    form_class = forms.ESUserCreationForm
    redirect_field_name = 'accounts/user_detail.html'
    # success_url = reverse_lazy('accounts:userdetails', kwargs={'pk': self.user.pk})
    template_name = 'accounts/edit_user.html'




class ESDeleteView(LoginRequiredMixin, DeleteView):
    model = models.ESUser
    success_url = reverse_lazy('home')
    template_name = 'accounts/delete_user.html'

djangoShopping/accounts/templates/accounts/delete_user.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}

{% block content %}
<div class="container">
   <h1>Confirm account removal</h1>
<div class="row" style="height:200px">
        <div class="col-md-8 userinfocol">
            <div id="userinfo">
                    <h5><span class="username">{{ user.username }}</span>, are you sure you want to delete your account?</h5>
                <hr style="border-top: 1px solid white;">
                <form method="POST">
                    {%  csrf_token %}
                <div class="stackedbutton"><button onclick="window.location='{% url 'accounts:userdetails' pk=user.pk %}'" type="button" class="btn btn-primary"><i class="fa-solid fa-times fa-1.5"></i> Cancel</button> </div>
                <br>
                <div class="stackedbutton"><button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash fa-1.5"></i> Delete</button> </div>
                </form>
            </div>


        </div>
        <div class="col-md-4 userinfocol" id="userphoto">
            <img id="photo_delete" src="{{ object.profile_pic.url }}">
        </div>



    </div>
</div>

{%  endblock %}

djangoShopping/accounts/templates/accounts/edit_user.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}

{% block content %}
<div class="container">
   <h1>Edit account details</h1>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-lg">Save changes</button>
    </form>
</div>

{%  endblock %}

djangoShopping/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}


{% block content %}
<div class="container">
   <h1>Log in</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-lg">Log in</button>

    </form>
</div>

{%  endblock %}

djangoShopping/accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%  load bootstrap5 %}

{% block content %}
<div class="container">
   <h1>Sign up</h1>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-lg">Sign up</button>
    </form>
</div>

{%  endblock %}

djangoShopping/accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}

{%  load bootstrap5 %}
{% load static %}
{% load tz %}


{% block content %}

    <h1 id="test">Account details</h1>
    <div class="row">
        <div class="col-md-4 userinfocol">
            <div id="userinfo">
                    <h2>Hi, <span class="username">{{ user.username }}</span>!</h2>
                <hr style="border-top: 1px solid white;">
                    <p id="line"><strong>Sex: </strong> {{ object.get_sex_display }}</p>
                    <p><strong>Origin: </strong> {{ object.origin }}</p>
                    <p><strong>Email: </strong> {{ object.email }} </p>
                    <p><strong>Last seen: </strong> {{ object.last_login|timezone:"Europe/Paris"  }} </p>
            </div>

            <div id="userbuttons">
                <h4 style="text-align:center">Manage your account</h4>
                <hr style="border-top: 1px solid white;">
                <a href="{%  url 'accounts:useredit' pk=object.pk %}">
                <div class="stackedbutton"><button class="btn btn-danger" style="background-color: #f39c12"><i class="fa-solid fa-edit fa-1.5"></i> Edit account</button> </div> </a>
                <br>
                <a href="{%  url 'accounts:userdelete' pk=object.pk %}">
               <div class="stackedbutton"><button type="button" class="btn btn-danger"><i class="fa-solid fa-trash fa-1.5"></i> Delete account</button> </div>
                </a>
            </div>
        </div>
        <div class="col-md-6 userinfocol" id="userphoto">
            <img id="photo" src="{{ object.profile_pic.url }}">
        </div>



    </div>


{%  endblock %}